version: '2'

services:
    nginx:
        build: ./nginx
        links:
            - node1:node1
            - node2:node2
        ports:
            - "80:80"
            - "443:443"
        env_file: .env
        volumes:
            - ./letsencrypt:/etc/letsencrypt
    node1:
        build: ./node_home
        ports:
            - "3000"
    node2:
        build: ./post
        ports:
            - "4000"
        volumes:
            - ./db:/src/db
            - ./media:/src/public/media           
